[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "miniinfer"
version = "0.1.0"
description = "a lightweight LLM inference framework implementation built from scratch"
authors = [{ name = "lzy", email = "tomlzy213@gmail.com" }]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "torch>=2.6.0",
    "triton>=3.0.0",
    "transformers>=4.51.0",
    "xxhash",
    "numpy>=2.2.4",
    "accelerate>=1.11.0",
    "flash-attn>=2.8.3",
    "ruff>=0.11.6",
    "pre-commit>=4.0.0",
    "pandas",
    "matplotlib",
    "pytest",
    "flashinfer-python",
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "."

[tool.setuptools.packages.find]
where = ["miniinfer"]
[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]
