"""MiniInfer package entrypoint with eager subpackage imports."""

from __future__ import annotations

import importlib
import os
from typing import Iterable

from .config import EngineConfig, PretrainedConfig, Qwen2Config, Qwen3Config
from .engine import (
  CapturedGraph,
  ChatTemplateHandler,
  CudaGraphRunner,
  DecodeState,
  FutureIndices,
  FutureMap,
  IncrementalBatchTokenizer,
  IncrementalDecoder,
  LLMEngine,
  ModelRunner,
  OverlapBatchRecord,
  OverlapExecutor,
  RequestOutput,
  StepOutput,
)
from .kvcache import (
  IKVCacheStorage,
  IPrefixCache,
  IRequestPool,
  ITokenAllocator,
  KVCacheManager,
  MHAKVCacheStorage,
  PagedTokenAllocator,
  RadixCache,
  RequestPool,
  TokenAllocator,
)
from .layers import (
  AttentionBackend,
  AttentionImpl,
  FlashAttention2Backend,
  FlashAttention2Metadata,
  FlashAttention3Backend,
  FlashAttention3Metadata,
  LMHead,
  RMSNorm,
  RotaryEmbedding,
  Sampler,
  VocabEmbedding,
  apply_activation,
  causal_mask,
  get_activation,
  get_attention,
  linear,
  softmax,
)
from .loader import DisabledTqdm, WeightLoaderMixin, load_hf_weight
from .models import (
  BaseModelOutput,
  Qwen2Attention,
  Qwen2ForCausalLM,
  Qwen2MLP,
  Qwen2Model,
  Qwen2TransformerBlock,
  Qwen3Attention,
  Qwen3ForCausalLM,
  Qwen3MLP,
  Qwen3Model,
  Qwen3TransformerBlock,
)
from .scheduler import (
  AddReqResult,
  BatchResult,
  BatchType,
  ChunkedReq,
  ForwardBatch,
  ForwardMode,
  PrefillAdder,
  Req,
  ScheduledBatch,
  Scheduler,
  clamp_position,
  compute_positions_extend,
)
from .utils import (
  SamplingParams,
  calc_max_total_tokens,
  dequantize_linear,
  make_model,
  profile_methods,
  shortcut_name_to_full_name,
  stage,
)

_EAGER_IMPORT_PACKAGES = (
  "config",
  "config.engine",
  "config.model",
  "loader",
  "layers",
  "layers.attention_backend",
  "kvcache",
  "scheduler",
  "models",
  "engine",
  "utils",
)


def eager_import_packages(packages: Iterable[str] = _EAGER_IMPORT_PACKAGES) -> None:
  """Import package entrypoints eagerly to front-load module initialization."""
  for package in packages:
    importlib.import_module(f"{__name__}.{package}")


if os.getenv("MINIINFER_EAGER_IMPORT", "1").strip().lower() not in {"0", "false", "off", "no"}:
  eager_import_packages()


__all__ = [
  "AddReqResult",
  "AttentionBackend",
  "AttentionImpl",
  "BaseModelOutput",
  "BatchResult",
  "BatchType",
  "CapturedGraph",
  "ChatTemplateHandler",
  "ChunkedReq",
  "CudaGraphRunner",
  "DecodeState",
  "DisabledTqdm",
  "EngineConfig",
  "FlashAttention2Backend",
  "FlashAttention2Metadata",
  "FlashAttention3Backend",
  "FlashAttention3Metadata",
  "ForwardBatch",
  "ForwardMode",
  "FutureIndices",
  "FutureMap",
  "IKVCacheStorage",
  "IPrefixCache",
  "IRequestPool",
  "ITokenAllocator",
  "IncrementalBatchTokenizer",
  "IncrementalDecoder",
  "KVCacheManager",
  "LLMEngine",
  "LMHead",
  "MHAKVCacheStorage",
  "ModelRunner",
  "OverlapBatchRecord",
  "OverlapExecutor",
  "PagedTokenAllocator",
  "PrefillAdder",
  "PretrainedConfig",
  "Qwen2Attention",
  "Qwen2Config",
  "Qwen2ForCausalLM",
  "Qwen2MLP",
  "Qwen2Model",
  "Qwen2TransformerBlock",
  "Qwen3Attention",
  "Qwen3Config",
  "Qwen3ForCausalLM",
  "Qwen3MLP",
  "Qwen3Model",
  "Qwen3TransformerBlock",
  "RMSNorm",
  "RadixCache",
  "Req",
  "RequestOutput",
  "RequestPool",
  "RotaryEmbedding",
  "Sampler",
  "SamplingParams",
  "ScheduledBatch",
  "Scheduler",
  "StepOutput",
  "TokenAllocator",
  "VocabEmbedding",
  "WeightLoaderMixin",
  "apply_activation",
  "calc_max_total_tokens",
  "causal_mask",
  "clamp_position",
  "compute_positions_extend",
  "dequantize_linear",
  "eager_import_packages",
  "get_activation",
  "get_attention",
  "linear",
  "load_hf_weight",
  "make_model",
  "profile_methods",
  "shortcut_name_to_full_name",
  "softmax",
  "stage",
]
